### ISSUE TITLE
a setup that works w/ netlify cms proxy

### ISSUE THREAD

**Issue by lastlink** [Knogobert/ntn-boilerplate#2]
* `npx netlify-cms-proxy-server`
* https://www.netlifycms.org/docs/beta-features/
* I was able to open /admin locally, but then got errors when opening each collection

## error
* Failed to load entry: API_ERROR: Unknown action unpublishedEntry

**Comment by Knogobert** [comment]
Nice! I'll look into this as soon as version ntn-boilerplate@2.0.0 is off the ground

**Comment by lastlink** [comment]
the publsh mode needs to be disabled
```yml
# publish_mode: editorial_workflow
backend:
  name: proxy
  proxy_url: http://localhost:8081/api/v1
  branch: master
```

idk if the proxy needs to run at the root of the project or not, but disabling the publish mode made it work
